# Generated by Django 5.0.4 on 2024-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_school_sdate_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Sdate_of_birth',
            field=models.DateField(default='2003-06-15'),
            preserve_default=False,
        ),
    ]
